sudo: false
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

before_install:
  - sudo apt-get install -y \
    autoconf \
    automake \
    build-essential \
    git \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libsqlite3-dev \
    m4 \
    openjdk-7-jdk \
    pkg-config \
    python-software-properties \
    unzip \
    zlib1g-dev
  # Checkout Infer
  - git clone https://github.com/facebook/infer.git
  - cd infer
  # Compile Infer
  - ./build-infer.sh java
  # Install Infer into your PATH
  - export PATH=`pwd`/infer/bin:$PATH


script:
  - mvn xml:check-format -P xml-check-format
  - mvn formatter:validate -P common-libs
#  - mvn -U clean install
#  - mvn -U -P common-libs jacoco:report coveralls:report
  - infer --racerd-only -- mvn -U clean install
