dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

addons:
  apt:
    packages:
      - autoconf
      - automake
      - build-essential
#     - git
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libsqlite3-dev
      - m4
#     - openjdk-7-jdk
      - pkg-config
      - python-software-properties
      - unzip
      - zlib1g-dev

before_install:
  - curl -kL https://raw.github.com/hcarty/ocamlbrew/master/ocamlbrew-install | env OCAMLBREW_FLAGS="-r" bash
  - source ~/ocamlbrew/ocaml-*/etc/ocamlbrew.bashrc
  - yes | opam init
    # Checkout Infer
  - git clone https://github.com/facebook/infer.git
  - pushd infer
  # Compile Infer
  - ./build-infer.sh java
  # Install Infer into your PATH
  - export PATH=`pwd`/infer/bin:$PATH
  # Remve example to avoid maven build error
  - rm -Rf examples


script:
  - popd
  - mvn xml:check-format -P xml-check-format
  - mvn formatter:validate -P common-libs
#  - mvn -U clean install
#  - mvn -U -P common-libs jacoco:report coveralls:report
  - infer --racerd-only -- mvn -U clean install
