sudo: false
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

before_install:
  - wget -O Dockerfile https://raw.githubusercontent.com/facebook/infer/master/docker/Dockerfile
  - wget -O run.sh https://raw.githubusercontent.com/facebook/infer/master/docker/run.sh
  - sh run.sh

script:
  - mvn xml:check-format -P xml-check-format
  - mvn formatter:validate -P common-libs
#  - mvn -U clean install
#  - mvn -U -P common-libs jacoco:report coveralls:report
  - infer --racerd-only -- mvn -U clean install
